In [1]:
import numpy as np
import math
from scipy import linalg

In [2]:
first_col = np.zeros(5000)
stim = np.random.randint(0,5000,50)
first_col[stim] = 1
first_row = first_col[:200]

In [3]:
D = linalg.toeplitz(first_row, first_col)
# stim
D[1,18:22]

array([0., 0., 0., 0.])

In [4]:
first_col = np.array([0,1,0,0,1,0]).astype(int)
first_row = np.zeros(5)
# first_row = first_col[:5]
D = linalg.toeplitz(first_col, first_row)
D

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [1., 0., 0., 1., 0.],
       [0., 1., 0., 0., 1.]])

In [5]:
D.T @ D

array([[2., 0., 0., 1., 0.],
       [0., 2., 0., 0., 1.],
       [0., 0., 1., 0., 0.],
       [1., 0., 0., 1., 0.],
       [0., 1., 0., 0., 1.]])

In [6]:
linalg.pinv(D.T @ D)

array([[ 1.,  0.,  0., -1.,  0.],
       [ 0.,  1.,  0.,  0., -1.],
       [ 0.,  0.,  1.,  0.,  0.],
       [-1.,  0.,  0.,  2.,  0.],
       [ 0., -1.,  0.,  0.,  2.]])

In [7]:
X = np.random.randint(2,7,(6,3))
X

array([[2, 5, 5],
       [3, 2, 3],
       [3, 3, 5],
       [2, 3, 6],
       [3, 2, 5],
       [5, 3, 2]])

In [8]:
D.T @ X

array([[6., 4., 8.],
       [8., 6., 7.],
       [2., 3., 6.],
       [3., 2., 5.],
       [5., 3., 2.]])

In [9]:
linalg.pinv(D.T @ D) @ (D.T @ X)

array([[ 3.,  2.,  3.],
       [ 3.,  3.,  5.],
       [ 2.,  3.,  6.],
       [ 0.,  0.,  2.],
       [ 2.,  0., -3.]])

In [10]:
first_col = np.array([0,0,1,0,0,0]).astype(int)
first_row = np.zeros(5)
D2 = linalg.toeplitz(first_col, first_row)

In [11]:
DD = np.hstack([D,D2])
DD

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 1., 0., 0., 0.],
       [1., 0., 0., 1., 0., 0., 0., 1., 0., 0.],
       [0., 1., 0., 0., 1., 0., 0., 0., 1., 0.]])

In [12]:
DD.T @ X

array([[6., 4., 8.],
       [8., 6., 7.],
       [2., 3., 6.],
       [3., 2., 5.],
       [5., 3., 2.],
       [3., 3., 5.],
       [2., 3., 6.],
       [3., 2., 5.],
       [5., 3., 2.],
       [0., 0., 0.]])

In [13]:
np.set_printoptions(suppress=True)
PP = linalg.pinv(DD.T @ DD) @ (DD.T @ X)
PP

array([[ 3. ,  2. ,  3. ],
       [ 2.2,  1.8,  2.4],
       [ 1. ,  1.5,  3. ],
       [-0. , -0. ,  1. ],
       [ 1.4,  0.6, -0.2],
       [ 0.8,  1.2,  2.6],
       [ 1. ,  1.5,  3. ],
       [-0. , -0. ,  1. ],
       [ 1.4,  0.6, -0.2],
       [ 0. ,  0. ,  0. ]])

In [14]:
PP = np.vsplit(PP, 2)
PP

[array([[ 3. ,  2. ,  3. ],
        [ 2.2,  1.8,  2.4],
        [ 1. ,  1.5,  3. ],
        [-0. , -0. ,  1. ],
        [ 1.4,  0.6, -0.2]]),
 array([[ 0.8,  1.2,  2.6],
        [ 1. ,  1.5,  3. ],
        [-0. , -0. ,  1. ],
        [ 1.4,  0.6, -0.2],
        [ 0. ,  0. ,  0. ]])]

In [15]:
# PP[0]
PP[0].T @ (D.T @ (D @ PP[0]))

array([[36.8 , 26.1 , 37.2 ],
       [26.1 , 19.25, 28.1 ],
       [37.2 , 28.1 , 44.6 ]])

In [16]:
PP[0].T @ D.T @ D @ PP[0]

array([[36.8 , 26.1 , 37.2 ],
       [26.1 , 19.25, 28.1 ],
       [37.2 , 28.1 , 44.6 ]])

In [17]:
a = PP[0].T @ D.T @ D
a@PP[0]

array([[36.8 , 26.1 , 37.2 ],
       [26.1 , 19.25, 28.1 ],
       [37.2 , 28.1 , 44.6 ]])

In [18]:
D @ PP[0]

array([[0. , 0. , 0. ],
       [3. , 2. , 3. ],
       [2.2, 1.8, 2.4],
       [1. , 1.5, 3. ],
       [3. , 2. , 4. ],
       [3.6, 2.4, 2.2]])

In [19]:
D

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [1., 0., 0., 1., 0.],
       [0., 1., 0., 0., 1.]])

In [20]:
linalg.pinv(D)

array([[ 0.,  1.,  0.,  0., -0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.,  0.],
       [-0., -1.,  0.,  0.,  1.,  0.],
       [ 0.,  0., -1.,  0.,  0.,  1.]])

In [21]:
linalg.pinv(D.T@D) @ D.T

array([[ 0.,  1.,  0.,  0., -0.,  0.],
       [ 0.,  0.,  1.,  0.,  0., -0.],
       [ 0.,  0.,  0.,  1.,  0.,  0.],
       [ 0., -1.,  0.,  0.,  1.,  0.],
       [ 0.,  0., -1.,  0.,  0.,  1.]])

In [23]:
linalg.inv(D.T @ D)

array([[ 1.,  0.,  0., -1., -0.],
       [ 0.,  1.,  0.,  0., -1.],
       [ 0.,  0.,  1.,  0., -0.],
       [-1.,  0.,  0.,  2., -0.],
       [ 0., -1.,  0.,  0.,  2.]])

In [26]:
linalg.inv(D.T @ D) @ D.T

array([[ 0.,  1.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.,  0.],
       [ 0., -1.,  0.,  0.,  1.,  0.],
       [ 0.,  0., -1.,  0.,  0.,  1.]])

In [27]:
linalg.pinv(D)

array([[ 0.,  1.,  0.,  0., -0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.,  0.],
       [-0., -1.,  0.,  0.,  1.,  0.],
       [ 0.,  0., -1.,  0.,  0.,  1.]])

In [75]:
A = np.array([[1,2,3],[-1,1,1],[1,1,1],[1,1,1]])
A

array([[ 1,  2,  3],
       [-1,  1,  1],
       [ 1,  1,  1],
       [ 1,  1,  1]])

In [83]:
# scipy.linalg.orth() doesn't actually seem
# to return the orthonormal set.
# Q = linalg.orth(A)

# home made orthonormal set!
def orthonormal(M):
    X = [M[:,0]]
    for i in range(1,M.shape[1]):
        col = M[:,i]
        x_i = col.copy()
        proj = []
        for j in range(i):
            x_j = X[j]
            x_i = x_i - (np.dot(col,x_j)/np.dot(x_j,x_j)) * x_j
            
        X.append(x_i)
        
    X = np.array(X).T
    return X

Q = orthonormal(A)
Q

array([[ 1.        ,  1.25      ,  0.42105263],
       [-1.        ,  1.75      , -0.21052632],
       [ 1.        ,  0.25      , -0.31578947],
       [ 1.        ,  0.25      , -0.31578947]])

In [84]:
R = Q.T @ A
R

array([[ 4.        ,  3.        ,  4.        ],
       [ 0.        ,  4.75      ,  6.        ],
       [-0.        ,  0.        ,  0.42105263]])

In [86]:
(Q @ R)/4

array([[ 1.        ,  2.234375  ,  2.91932133],
       [-1.        ,  1.328125  ,  1.60283934],
       [ 1.        ,  1.046875  ,  1.341759  ],
       [ 1.        ,  1.046875  ,  1.341759  ]])

In [79]:
Q, R = linalg.qr(A, mode='economic')
print(Q)
print(R)

[[-0.5        -0.57353933  0.64888568]
 [ 0.5        -0.80295507 -0.32444284]
 [-0.5        -0.11470787 -0.48666426]
 [-0.5        -0.11470787 -0.48666426]]
[[-2.         -1.5        -2.        ]
 [ 0.         -2.17944947 -2.75298881]
 [ 0.          0.          0.64888568]]


In [80]:
Q @ R

array([[ 1.,  2.,  3.],
       [-1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [47]:
vecs = np.array([[1,2,3],[2,2,2],[1,1,1]]).astype(float)
print(vecs)
norm = np.apply_along_axis(np.linalg.norm, 0, vecs)
print(norm)
vecs /= norm
print(vecs)

[[1. 2. 3.]
 [2. 2. 2.]
 [1. 1. 1.]]
[2.44948974 3.         3.74165739]
[[0.40824829 0.66666667 0.80178373]
 [0.81649658 0.66666667 0.53452248]
 [0.40824829 0.33333333 0.26726124]]


In [52]:
for i in range(1):
    print(i)

0
